import {StyleSheet} from 'react-native';
import {widthAdapter, heightAdapter, fontscale} from '../uttils/adapterUtil';
import Colors from '../uttils/Colors';
import fontFamily from '../uttils/FontFamily';

const styles = StyleSheet.create({
  trendingContainer: {
    flex: 1,
    marginLeft: widthAdapter(40),
    marginRight: widthAdapter(40),
    // paddingTop: heightAdapter(50),
  },
  trendingList: {
    marginTop: heightAdapter(50),
    marginBottom: heightAdapter(160),
  },
  trendingItemContainer: {
    flexDirection: 'row',
    height: heightAdapter(400),
    marginBottom: widthAdapter(75),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    borderRadius: widthAdapter(4),
    borderWidth: 1,
    borderBottomWidth: widthAdapter(5),
    borderColor: Colors.gray,
    // paddingTop: widthAdapter(30),
    // paddingBottom: widthAdapter(30),
    // paddingLeft: widthAdapter(10),
    // borderWidth: 1,
    // borderColor: 'red',
  },
  trendingDetailsContainer: {
    width: '70%',
    // height: '100%',
  },
  trendingImageContainer: {
    width: '30%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trendingImage: {
    height: heightAdapter(100),
    width: widthAdapter(100),
  },
  trendingProduct: {
    flexDirection: 'row',
    width: '100%',
    height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    // borderColor: 'red',
    // borderWidth: 1,
    marginBottom: heightAdapter(20),
  },
  trendingProductTxt: {
    fontFamily: fontFamily.primaryFontFamily,
    color: '#333',
    fontWeight: '700',
    fontSize: widthAdapter(35),
  },
  dotWithTick: {
    height: widthAdapter(40),
    width: widthAdapter(40),
    // backgroundColor: Colors.primaryAppColor,
    // borderRadius: 100,
    marginRight: widthAdapter(20),
    marginLeft: widthAdapter(20),
  },
  amountStatusContainer: {
    flexDirection: 'row',
    width: '100%',
    // height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: widthAdapter(90),
    marginBottom: heightAdapter(20),
  },
  amountLabel: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.black,
    fontWeight: '500',
  },
  dollar: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: 'green',
    fontWeight: '500',
  },
  amount: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.primaryAppColor,
    fontWeight: '500',
  },
  statusLabel: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.primaryAppColor,
    fontWeight: '500',
  },
  status: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: 'green',
    fontWeight: '500',
  },
  trendingStatusContainer: {
    flexDirection: 'row',
    width: '100%',
    height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: widthAdapter(90),
    marginBottom: heightAdapter(20),
  },
  trendingSalesContainer: {
    flexDirection: 'row',
    width: '100%',
    height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: widthAdapter(90),
    marginBottom: heightAdapter(20),
  },
  trendingSalesLabel: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.black,
    fontWeight: '500',
  },

  productDetailsContainer: {
    flex: 1,
    marginLeft: widthAdapter(40),
    marginRight: widthAdapter(40),
    paddingTop: heightAdapter(50),
    // borderColor: 'red',
    // borderWidth: 1,
  },
  productNameLabel: {
    fontFamily: fontFamily.primaryFontFamily,
    fontSize: fontscale(15),
    color: '#737373',
    // lineHeight: 1,
  },
  productName: {
    fontFamily: fontFamily.primaryFontFamily,
    fontSize: fontscale(25),
    // color: '#737373',
  },
  amountContainer: {
    flexDirection: 'row',
    // borderColor: 'red',
    // borderWidth: 1,
    justifyContent: 'flex-end',
  },
  commissionAmountLabel: {
    fontFamily: fontFamily.primaryFontFamily,
    fontSize: fontscale(15),
    color: '#737373',
    // lineHeight: 1,
  },
  commissionAmount: {
    fontSize: fontscale(21),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.primaryAppColor,
    fontWeight: '500',
  },
  commissionStatusContainer: {
    flexDirection: 'row',
    // borderColor: 'red',
    // borderWidth: 1,
    justifyContent: 'flex-end',
  },
  imageContainer: {
    flexDirection: 'row',
    borderColor: '#ccc',
    borderWidth: 0.3,
    justifyContent: 'center',
    padding: widthAdapter(20),
  },
  productImage: {
    height: heightAdapter(150),
    width: widthAdapter(200),
  },
  addWishListBtn: {
    borderWidth: 1,
    borderColor: '#ccc',
    width: widthAdapter(300),
    height: heightAdapter(75),
    borderRadius: heightAdapter(5),
    backgroundColor: '#fff',
  },
  addWishListBtnText: {
    color: '#333',
    fontSize: fontscale(13),
    fontFamily: fontFamily.primaryFontFamily,
  },
  labelContainer: {
    flexDirection: 'row',
    width: '100%',
  },
  viewStyle: {
    width: '50%',
    backgroundColor: '#f9f9f9',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    paddingLeft: widthAdapter(20),
    paddingRight: widthAdapter(20),
  },
  label: {
    fontSize: fontscale(15),
    fontWeight: 'bold',
    fontFamily: fontFamily.primaryFontFamily,
  },
  value: {
    fontSize: fontscale(15),
    fontFamily: fontFamily.primaryFontFamily,
  },
  productInfoContainer: {
    borderColor: '#ccc',
    borderWidth: 0.3,
  },
});

export default styles;
