import {StyleSheet} from 'react-native';
import {widthAdapter, heightAdapter, fontscale} from '../uttils/adapterUtil';
import Colors from '../uttils/Colors';
import fontFamily from '../uttils/FontFamily';

const styles = StyleSheet.create({
  commissionContainer: {
    flex: 1,
    marginLeft: widthAdapter(40),
    marginRight: widthAdapter(40),
    // paddingTop: heightAdapter(50),
  },
  dropdownContainer: {
    borderWidth: 1,
    borderColor: '#737373',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderRadius: widthAdapter(3),
    borderBottomWidth: widthAdapter(4),
    // zIndex: 100,
    backgroundColor: '#333333',

    width: widthAdapter(600),
    height: heightAdapter(100),
    // zIndex: 100,
    // borderColor: 'red',
    // borderWidth: 1,
  },
  dropdownAndFilterContainer: {
    flexDirection: 'row',
    width: widthAdapter(750),
    // borderWidth: 1,
    // borderColor: 'blue',
    zIndex: 999,
  },
  image: {
    height: heightAdapter(40),
    width: widthAdapter(40),
    borderColor: 'red',
    borderWidth: 1,
    marginRight: widthAdapter(10),
  },
  selectionBox: {
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: widthAdapter(20),
    paddingRight: widthAdapter(20),
    backgroundColor: '#333333',
  },
  selectedValue: {
    fontSize: fontscale(20),
    fontFamily: fontFamily.primaryFontFamily,
    color: 'white', //'#737373',
    fontWeight: 'bold',
    marginLeft: widthAdapter(20),
  },
  transparentView: {
    flex: 1,
    position: 'absolute',
    top: widthAdapter(-35),
    bottom: 0,
    left: widthAdapter(-35),
    right: widthAdapter(-35),
    backgroundColor: 'gray',
    zIndex: 1,
    opacity: 0.1,
  },
  segmentItemRow: {
    width: '100%',
    height: heightAdapter(75),
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderColor: 'gray',
    borderBottomWidth: 1,
    // backgroundColor: Colors.white,
    backgroundColor: '#eee',
  },
  segmentItemText: {
    fontSize: fontscale(20),
    fontFamily: fontFamily.primaryFontFamily,
    color: '#737373',
    fontWeight: 'bold',
  },
  segmentedView: {
    width: '100%',
    position: 'absolute',
    top: heightAdapter(99),
    left: widthAdapter(0),
    borderBottomLeftRadius: widthAdapter(8),
    borderBottomRightRadius: widthAdapter(8),
    // backgroundColor: Colors.white,
    borderColor: '#737373',
    backgroundColor: '#eee',
  },
  commissionList: {
    marginTop: heightAdapter(50),
    marginBottom: heightAdapter(160),
  },
  commissionItemContainer: {
    flexDirection: 'row',
    // height: heightAdapter(350),
    marginBottom: widthAdapter(75),
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    borderRadius: widthAdapter(4),
    borderWidth: 1,
    borderBottomWidth: widthAdapter(5),
    borderColor: '#737373',
    paddingTop: widthAdapter(30),
    paddingBottom: widthAdapter(30),
    paddingLeft: widthAdapter(10),
  },
  commissionDetailsContainer: {
    width: '100%',
    // height: '100%',
  },
  customerDetails: {
    width: '100%',
    // height: '20%', //heightAdapter(60),
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    paddingLeft: widthAdapter(20),
    paddingRight: widthAdapter(20),
    paddingTop: heightAdapter(30),
  },
  emailphoneIcon: {
    // height: widthAdapter(20),
    // width: widthAdapter(20),
    // borderWidth: 1,
    // borderColor: 'red',
    marginRight: widthAdapter(5),
  },
  customerDetailsTxt: {
    fontFamily: fontFamily.primaryFontFamily,
    color: '#737373',
    fontWeight: 'bold',
    fontSize: fontscale(15),
  },
  customerDetailsLabel: {
    fontFamily: fontFamily.primaryFontFamily,
    color: '#737373',
    fontWeight: '400',
    fontSize: fontscale(15),
    // lineHeight: 2,
  },
  statusFilterContainer: {
    marginLeft: widthAdapter(70),
    width: widthAdapter(70),
    borderColor: '#737373',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#737373',
    borderRadius: 100,
  },
  sliderContainer: {
    flex: 1,
    // alignItems: 'center',
    // justifyContent: 'center',
    // padding: widthAdapter(30),
    paddingTop: heightAdapter(20),
    zIndex: 100,
  },
  sliderBtnStyle: {
    height: heightAdapter(50),
    width: widthAdapter(700),
    marginRight: widthAdapter(30),
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginLeft: widthAdapter(20),
    backgroundColor: '#f2f2f2',
    borderRadius: 0,
    // borderRadius: widthAdapter(50),
  },
  sliderBtnContainer: {
    flexDirection: 'row',
    width: '100%',
    // height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    // borderColor: 'blue',
    // borderWidth: 1,
    paddingLeft: widthAdapter(20),
    backgroundColor: '#f2f2f2',
  },
  sliderBtnTxtStyle: {
    color: 'black',
  },
});

export default styles;
