import {StyleSheet} from 'react-native';
import {widthAdapter, heightAdapter, fontscale} from '../uttils/adapterUtil';
import Colors from '../uttils/Colors';
import fontFamily from '../uttils/FontFamily';

const styles = StyleSheet.create({
  referralsContainer: {
    flex: 1,
    marginLeft: widthAdapter(40),
    marginRight: widthAdapter(40),
    paddingTop: heightAdapter(50),
  },
  dropdownContainer: {
    width: '100%',
    height: heightAdapter(100),
    borderWidth: 1,
    borderColor: '#737373',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderRadius: widthAdapter(3),
    borderBottomWidth: widthAdapter(4),
    zIndex: 100,
    backgroundColor: '#333333',
  },
  image: {
    height: heightAdapter(40),
    width: widthAdapter(40),
    borderColor: 'red',
    borderWidth: 1,
    marginRight: widthAdapter(10),
  },
  selectionBox: {
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    paddingLeft: widthAdapter(10),
    backgroundColor: '#333333',
  },
  selectedValue: {
    fontSize: fontscale(20),
    fontFamily: fontFamily.primaryFontFamily,
    color: 'white', //'#737373',
    fontWeight: 'bold',
  },
  transparentView: {
    flex: 1,
    position: 'absolute',
    top: widthAdapter(-35),
    bottom: 0,
    left: widthAdapter(-35),
    right: widthAdapter(-35),
    backgroundColor: 'gray',
    zIndex: 1,
    opacity: 0.1,
  },
  segmentItemRow: {
    width: '100%',
    height: heightAdapter(75),
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderColor: 'gray',
    borderBottomWidth: 1,
    // backgroundColor: Colors.white,
    backgroundColor: '#eee',
  },
  segmentItemText: {
    fontSize: fontscale(20),
    fontFamily: fontFamily.primaryFontFamily,
    color: '#737373',
    fontWeight: 'bold',
  },
  segmentedView: {
    width: '100%',
    position: 'absolute',
    top: heightAdapter(99),
    left: widthAdapter(0),
    borderBottomLeftRadius: widthAdapter(8),
    borderBottomRightRadius: widthAdapter(8),
    // backgroundColor: Colors.white,
    borderColor: '#737373',
    backgroundColor: '#eee',
  },
  referralList: {
    marginTop: heightAdapter(50),
    marginBottom: heightAdapter(160),
  },
  referralsItemContainer: {
    // flexDirection: 'row',
    // height: heightAdapter(450),
    marginBottom: widthAdapter(30),
    // alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
    borderRadius: widthAdapter(4),
    // borderWidth: 1,
    borderBottomWidth: widthAdapter(1),
    borderBottomColor: '#eee',
    // borderColor: Colors.gray,
    // paddingTop: widthAdapter(30),
    // paddingBottom: widthAdapter(30),
    // paddingLeft: widthAdapter(10),
  },
  expandCollapseHeader: {
    flexDirection: 'row',
    height: heightAdapter(100),
    // borderColor: 'red',
    // borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: widthAdapter(20),
    paddingRight: widthAdapter(20),
  },
  expandCollapseLeftChild: {
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  childTxt: {
    fontSize: fontscale(20),
    fontFamily: fontFamily.primaryFontFamily,
    // color: 'green',
    fontWeight: 'bold',
  },
  expandCollapseRightChild: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  regStatus: {
    height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: widthAdapter(30),
    borderRadius: widthAdapter(50),
    backgroundColor: '#32CD32',
    paddingRight: widthAdapter(20),
    paddingLeft: widthAdapter(20),
  },
  regStatusText: {
    fontSize: fontscale(15),
    color: Colors.white,
    fontFamily: fontFamily.primaryFontFamily,
    fontWeight: 'bold',
    // borderColor: 'red',
    // borderWidth: 1,
    // margin: widthAdapter(20),
  },
  dropDownIcon: {
    height: widthAdapter(40),
    width: widthAdapter(40),
    borderColor: 'red',
    borderWidth: 1,
  },
  referralsDetailsContainer: {
    // width: '80%',
    // height: '100%',
    // borderWidth: 1,
    // borderColor: 'red',
    height: 0,
    // position: 'absolute',
    // top: heightAdapter(100),
    // right: 0,
    // left: 0,
    backgroundColor: '#eee',
  },
  customerDetails: {
    width: '100%',
    // height: '20%', //heightAdapter(60),
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    paddingLeft: widthAdapter(20),
    paddingRight: widthAdapter(20),
  },
  emailphoneIcon: {
    // height: widthAdapter(20),
    // width: widthAdapter(20),
    // borderWidth: 1,
    // borderColor: 'red',
    marginRight: widthAdapter(5),
  },
  customerDetailsTxt: {
    fontFamily: fontFamily.primaryFontFamily,
    color: '#333',
    // fontWeight: '700',
    fontSize: fontscale(20),
  },
  customerDetailsLabel: {
    fontFamily: fontFamily.primaryFontFamily,
    color: '#333',
    // fontWeight: '700',
    fontSize: fontscale(20),
  },
});

export default styles;
