export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const USER_LOGIN = 'USER_LOGIN';
export const SAGA_AUTHENTICATE_USER = 'SAGA_AUTHENTICATE_USER';
export const SAGA_GET_DASHBOARD_DATA = 'SAGA_GET_DASHBOARD_DATA';
export const STORE_DASHBOARD_DATA = 'STORE_DASHBOARD_DATA';
export const STORE_PRODUCTS_LIST = 'STORE_PRODUCTS_LIST';
export const SAGA_GET_PRODUCTS_LIST = 'SAGA_GET_PRODUCTS_LIST';
export const SAGA_GET_PROFILE_INFO = 'SAGA_GET_PROFILE_INFO';
export const STORE_PROFILE_INFO = 'STORE_PROFILE_INFO';
export const SAGA_SAVE_PROFILE_INFO = 'SAGA_SAVE_PROFILE_INFO';
export const SAGA_REGISTER_USER = 'SAGA_REGISTER_USER';
export const SAGA_GET_COMMISSION_DATE_FILTER =
  'SAGA_GET_COMMISSION_DATE_FILTER';
export const SAGA_GET_COMMISSION_LIST = 'SAGA_GET_COMMISSION_LIST';
export const STORE_COMMISSION_DATE_FILTER = 'STORE_COMMISSION_DATE_FILTER';
export const STORE_COMMISSION_LIST = 'STORE_COMMISSION_LIST';
