export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const USER_LOGIN = 'USER_LOGIN';
export const SAGA_AUTHENTICATE_USER = 'SAGA_AUTHENTICATE_USER';
export const SAGA_GET_DASHBOARD_DATA = 'SAGA_GET_DASHBOARD_DATA';
export const STORE_DASHBOARD_DATA = 'STORE_DASHBOARD_DATA';
export const SAGA_GET_PENDING_TASK_DATA = 'SAGA_GET_PENDING_TASK_DATA';
export const STORE_PENDING_TASK_DATA = 'STORE_PENDING_TASK_DATA';
export const STORE_PRODUCTS_LIST = 'STORE_PRODUCTS_LIST';
export const SAGA_GET_PRODUCTS_LIST = 'SAGA_GET_PRODUCTS_LIST';
export const SAGA_GET_PROFILE_INFO = 'SAGA_GET_PROFILE_INFO';
export const STORE_PROFILE_INFO = 'STORE_PROFILE_INFO';
export const SAGA_SAVE_PROFILE_INFO = 'SAGA_SAVE_PROFILE_INFO';
export const SAGA_REGISTER_USER = 'SAGA_REGISTER_USER';
export const SAGA_GET_COMMISSION_DATE_FILTER =
  'SAGA_GET_COMMISSION_DATE_FILTER';
export const SAGA_GET_COMMISSION_LIST = 'SAGA_GET_COMMISSION_LIST';
export const STORE_COMMISSION_DATE_FILTER = 'STORE_COMMISSION_DATE_FILTER';
export const STORE_COMMISSION_LIST = 'STORE_COMMISSION_LIST';
export const SAGA_VERIFY_USER_EMAIL = 'SAGA_VERIFY_USER_EMAIL';
export const SAGA_GET_TRENDING_PRODUCTS = 'SAGA_GET_TRENDING_PRODUCTS';
export const STORE_TRENDING_PRODUCTS_LIST = 'STORE_TRENDING_PRODUCTS_LIST';
export const SAGA_GET_REFERRAL_REG_STATUS_FILTER =
  'SAGA_GET_REFERRAL_REG_STATUS_FILTER';
export const SAGA_GET_REFERRAL_DATE_FILTER = 'SAGA_GET_REFERRAL_DATE_FILTER';
export const SAGA_GET_REP_REFERRED_USERS_LIST = 'SAGA_GET_REP_REFERRED_USERS_LIST';
export const SAGA_GET_REFERRAL_COMMISSION_LIST =
  'SAGA_GET_REFERRAL_COMMISSION_LIST';
export const SAGA_POST_REFERRAL_USER = 'SAGA_POST_REFERRAL_USER';
export const STORE_REFERRAL_REG_STATUS_FILTER =
  'STORE_REFERRAL_REG_STATUS_FILTER';
export const STORE_REFERRAL_DATE_FILTER = 'STORE_REFERRAL_DATE_FILTER';
export const STORE_REP_REFERRED_USERS_LIST = 'STORE_REP_REFERRED_USERS_LIST';
export const STORE_REFERRAL_COMMISSION_LIST = 'STORE_REFERRAL_COMMISSION_LIST';
export const STORE_REFERRAL_USER = 'STORE_REFERRAL_USER';
export const STORE_USER_DETAILS = 'STORE_USER_DETAILS';
export const SAGA_GET_PAYOUT_DATE_FILTER = 'SAGA_GET_PAYOUT_DATE_FILTER';
export const SAGA_GET_PAYOUT_HISTORY_LIST = 'SAGA_GET_PAYOUT_HISTORY_LIST';
export const STORE_PAYOUT_DATE_FILTER = 'STORE_PAYOUT_DATE_FILTER';
export const STORE_PAYOUT_HISTORY_LIST = 'STORE_PAYOUT_HISTORY_LIST';
export const SAGA_GET_PAYOUT_DETAILS = 'SAGA_GET_PAYOUT_DETAILS';
export const STORE_PAYOUT_DETAILS = 'STORE_PAYOUT_DETAILS';

export const SAGA_SEND_PWD_MOBILE_VERIFICATION_CODE = 'SAGA_SEND_PWD_MOBILE_VERIFICATION_CODE';
export const SAGA_VERIFY_PWD_MOBILE_VERIFICATION_CODE = 'SAGA_VERIFY_PWD_MOBILE_VERIFICATION_CODE';
export const SAGA_FORGOT_PWD_CHANGE_PASSWORD = 'SAGA_FORGOT_PWD_CHANGE_PASSWORD';
export const STORE_SEND_PWD_MOBILE_VERIFICATION_CODE = 'STORE_SEND_PWD_MOBILE_VERIFICATION_CODE';

export const SAGA_GET_USER_MOBILE_DETAIL = 'SAGA_GET_USER_MOBILE_DETAIL';
export const SAGA_SEND_USER_MOBILE_VERIFICATION_CODE = 'SAGA_SEND_USER_MOBILE_VERIFICATION_CODE';
export const SAGA_VERIFY_USER_MOBILE_VERIFICATION_CODE = 'SAGA_VERIFY_USER_MOBILE_VERIFICATION_CODE';
export const SAGA_GET_USER_EMAIL_DETAIL = 'SAGA_GET_USER_EMAIL_DETAIL';
export const SAGA_SEND_USER_EMAIL_VERIFICATION_CODE = 'SAGA_SEND_USER_EMAIL_VERIFICATION_CODE';
export const SAGA_VERIFY_USER_EMAIL_VERIFICATION_CODE = 'SAGA_VERIFY_USER_EMAIL_VERIFICATION_CODE';
export const STORE_USER_EMAIL_VERIFIED = 'STORE_USER_EMAIL_VERIFIED';
export const STORE_SEND_USER_EMAIL_VERIFICATION_CODE = 'STORE_SEND_USER_EMAIL_VERIFICATION_CODE';
export const STORE_USER_MOBILE_VERIFIED = 'STORE_USER_MOBILE_VERIFIED';
export const STORE_SEND_USER_MOBILE_VERIFICATION_CODE = 'STORE_SEND_USER_MOBILE_VERIFICATION_CODE';

export const SAGA_GET_FORM_DEFENITION_DETAILS_DATA = 'SAGA_GET_FORM_DEFENITION_DETAILS_DATA';
export const STORE_FORM_DEFENITION_DETAILS_DATA = 'STORE_FORM_DEFENITION_DETAILS_DATA';
export const SAGA_POST_TASK_ENTRY_DATA = 'SAGA_POST_TASK_ENTRY_DATA';

export const SAGA_GET_PRODUCT_DETAILS_DATA = 'SAGA_GET_PRODUCT_DETAILS_DATA';
export const STORE_PENDING_TASK_PRODUCT_DETAILS_DATA = 'STORE_PENDING_TASK_PRODUCT_DETAILS_DATA';
export const STORE_TRENDING_PRODUCTS_DETAILS = 'STORE_TRENDING_PRODUCTS_DETAILS';

export const SAGA_GET_GOOGLE_MAP_COORDINATES = 'SAGA_GET_GOOGLE_MAP_COORDINATES';
export const STORE_GOOGLE_MAP_COORDINATES = 'STORE_GOOGLE_MAP_COORDINATES';
export const SAGA_SAVE_SUGGESTION = 'SAGA_SAVE_SUGGESTION';

export const STORE_USER_MOBILE_DETAILS = 'STORE_USER_MOBILE_DETAILS';
export const STORE_USER_EMAIL_DETAILS = 'STORE_USER_EMAIL_DETAILS';

export const SAGA_STORE_PROVIDERS = 'SAGA_STORE_PROVIDERS';
export const SAGA_GET_PROVIDERS = 'SAGA_GET_PROVIDERS';

export const SET_INITIAL_ROUTE = 'SET_INITIAL_ROUTE';
