export default {
  loginScreen: 'Login Screen',
  homeScreen: 'Home Screen',
  detailsScreen: 'Details Screen',
  mapView: 'Map View',
  login: {
    userInfo: 'Sign in with your existing account',
    headerTitle: 'Login',
    emailPlaceHolder: 'Enter email',
    passwordPlaceHolder: 'Enter password',
    loginBtnName: 'Sign in',
    signUpNow: 'Sign up now',
    forgotPwd: 'Forgot your password?',
  },
  homePage: {
    headerTitle: 'XYZ Pays',
    hello: 'Hello,',
    taskBtnPrefixText: 'You have',
    taskBtnPostfixText: 'Pending Tasks',
    paymentApproved: 'APPROVED',
    paymentPaid: 'PAID',
    paymentPending: 'PENDING',
    paymentDenied: 'DENIED',

    paymentApprovedDescription1: 'Commission',
    paymentApprovedDescription2: 'in',
    paymentApprovedDescription3: 'your',
    paymentApprovedDescription4: 'XYZ Account',

    paymentPaidDescription1: 'Commission',
    paymentPaidDescription2: 'transfered',
    paymentPaidDescription3: 'to your',
    paymentPaidDescription4: 'Paypal Account',

    paymentPendingDescription1: 'Commission',
    paymentPendingDescription2: 'awaiting',
    paymentPendingDescription3: 'to',
    paymentPendingDescription4: 'receive',

    paymentDeniedDescription1: 'Commission',
    paymentDeniedDescription2: 'denied',
    paymentDeniedDescription3: 'by your',
    paymentDeniedDescription4: 'Vendor',

    View: 'View',
    taskBtnName: 'Start Task',
  },
  userRegistration: {
    headerTitle: 'New Registration',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    email: 'Login Email',
    password: 'Password',
    retypePassword: 'Retype Password',
    registerBtnName: 'Register',
  },
  forgotPassword: {
    headerTitle: 'Forgot Password',
    userInfoStep1: 'XYZPays Password Recovery - Step 1',
    step1: 'Enter your registered Email Id',
    next: 'Next',
  },
  commission: {
    headerTitle: 'Commissions',
    dropdownAll: 'All',
    dropdown7Days: 'Last 7 Days',
    dropdownLast2Weeks: 'Last 2 Weeks',
    dropdownLast3Weeks: 'Last 3 Weeks',
    dropdownLast1Month: 'Last 1 Month',
    dropdownLast3Months: 'Last 3 Months',
    paymentDate: 'Payment Date: ',
    accountNo: 'Acc No: ',
    reason: 'Reason: ',
    amount: 'Amount:',
    status: 'Status:',
    currencySymbol: '$',
  },
  trending: {
    headerTitle: 'Trending',
    amount: 'Amount:',
    status: 'Status:',
    currencySymbol: '$',
    sales: 'Sales:',
  },
  taskEntryPage: {
    headerTitle: 'Task Entry',
    active: 'Active',
    sku: 'SKU',
    saveBtnName: 'Save',
  },
  profile: {
    headerTitle: 'My Profile',
    editProfile: 'Edit Profile',
    accountInfoLabel: 'Account Info',
    repId: 'Rep Id',
    registrationType: 'Registration Type',
    status: 'Status',
    registeredOn: 'Registered On',
    productAccess: 'Product Access',
    createdBy: 'Created By',
    contactDetails: 'Contact Details',
    address: 'Address',
    stateCity: 'State/City',
    mobile: 'Mobile',
    paypalEmail: 'Paypal Email',
    website: 'Website',
    interest: 'Interest',
  },
  editProfile: {
    headerTitle: 'Edit Profile',
    editPhoto: 'Choose Photo',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    email: 'Login Email',
    address: 'Address',
    state: 'State',
    city: 'City',
    website: 'Website',
    interest: 'Add it to your Interest',
    zipCode: 'Zip Code',
    updateBtnName: 'Update',
  },
  referAndEarn: {
    headerTitle: 'Refer & Earn',
    userInfo: 'Refer User & Earn Money',
    name: '* Name',
    mobileNumber: '* Mobile Number',
    email: '* Email',
    sendBtnName: 'Send Message',
    linkBtn: 'Click here to view your Referrals',
  },
  myReferrals: {
    headerTitle: 'My Referrals',
    dropdownAll: 'All',
    registered: 'Registered',
    notRegistered: 'Not Registered',
    referredOn: 'Referred On: ',
    registeredOn: 'Registered On: ',
  },
  referralCommissions: {
    headerTitle: 'Referral Comissions',
    rferredUser: 'Referred User: ',
    referralCommission: 'Referral Commission: ',
    status: 'Status: ',
    email: 'Email: ',
    phone: 'Phone: ',
    paymentDate: 'Payment Date: ',
  },
  contactUs: {
    headerTitle: 'Contact Us',
    findUsBtnName: 'Find Us',
    submitBtnName: 'Submit',
    subject: 'Subject',
    message: 'Message',
  },
  payoutHistory: {
    headerTitle: 'Payout History',
    transferBtnName: 'Transfer to you Paypal Account',
    emailId: 'Your Paypal email Id: ',
  },
  faq: {
    headerTitle: 'FAQ',
  },
  common: {
    placeHolder: 'Enter value',
  },
};
