export default {
  loginScreen: 'Login Screen',
  homeScreen: 'Home Screen',
  detailsScreen: 'Details Screen',
  mapView: 'Map View',
  login: {
    userInfo: 'Sign in with your existing account',
    headerTitle: 'Login',
    emailPlaceHolder: 'Enter email',
    passwordPlaceHolder: 'Enter password',
    loginBtnName: 'Sign in',
    signUpNow: 'Sign up now',
    forgotPwd: 'Forgot your password?',
  },
  homePage: {
    headerTitle: 'XYZ Pays',
    hello: 'Hello,',
    taskBtnPrefixText: 'You have',
    taskBtnPostfixText: 'Pending Tasks',
    paymentApproved: 'APPROVED',
    paymentPaid: 'PAID',
    paymentPending: 'PENDING',
    paymentDenied: 'DENIED',

    paymentApprovedDescription1: 'Commission',
    paymentApprovedDescription2: 'in',
    paymentApprovedDescription3: 'your',
    paymentApprovedDescription4: 'XYZ Account',

    paymentPaidDescription1: 'Commission',
    paymentPaidDescription2: 'transfered',
    paymentPaidDescription3: 'to your',
    paymentPaidDescription4: 'Paypal Account',

    paymentPendingDescription1: 'Commission',
    paymentPendingDescription2: 'awaiting',
    paymentPendingDescription3: 'to',
    paymentPendingDescription4: 'receive',

    paymentDeniedDescription1: 'Commission',
    paymentDeniedDescription2: 'denied',
    paymentDeniedDescription3: 'by your',
    paymentDeniedDescription4: 'Vendor',

    View: 'View',
    taskBtnName: 'Start Task',
  },
  userRegistration: {
    headerTitle: 'New Registration',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    email: 'Login Email',
    password: 'Password',
    retypePassword: 'Retype Password',
    registerBtnName: 'Register',
    providers: 'Providers',
  },
  forgotPassword: {
    headerTitle: 'Forgot Password',
    userInfo: 'XYZPays Password Recovery',
    userInfoStep: 'Step ',
    step1: 'Enter your registered Email Id',
    step2: 'Select how would you like to receive password reset instructions',
    step3: 'Verification Code sent to your registered mobile number:',
    step4: 'Enter your new Credentials',
    next: 'Next',
    sendVerification: 'Send Verification Code',
    madeMistake: 'Made an Mistake? Start Fresh',
    recoveryMsg: 'Recovery Mobile Number',
    verificatioCodePlaceHolder: 'Enter Code Sent to your Mobile Number',
    step3Next: 'Verify Code',
    newPasswordPlaceHolder: 'New Password',
    confirmPasswordPlaceHolder: 'Confirm Password',
    pwdError: 'New Password and Confirm Password should be same.',
    step4next: 'Reset Password',
  },
  commission: {
    headerTitle: 'Commissions',
    userInfo: 'Your Commission Details',
    dropdownAll: 'All',
    dropdown7Days: 'Last 7 Days',
    dropdownLast2Weeks: 'Last 2 Weeks',
    dropdownLast3Weeks: 'Last 3 Weeks',
    dropdownLast1Month: 'Last 1 Month',
    dropdownLast3Months: 'Last 3 Months',
    paymentDate: 'Payment Date: ',
    accountNo: 'Acc No: ',
    reason: 'Reason: ',
    amount: 'Amount:',
    status: 'Status:',
    currencySymbol: '$',
    filterAll: 'All',
    filterPaid: 'Paid',
    filterPending: 'Pending',
    filterDenied: 'Denied',
  },
  trending: {
    headerTitle: 'Trending',
    userInfo: 'Trending Products',
    amount: 'Amount:',
    status: 'Status:',
    currencySymbol: '$',
    sales: 'Sales:',
  },
  taskEntryPage: {
    headerTitle: 'Task Entry',
    active: 'Active',
    sku: 'SKU',
    saveBtnName: 'Save',
  },
  profile: {
    headerTitle: 'My Profile',
    userInfo: 'Your Profile Informations',
    editProfile: 'Edit Profile',
    accountInfoLabel: 'Account Info',
    repId: 'Rep Id',
    registrationType: 'Registration Type',
    status: 'Status',
    registeredOn: 'Registered On',
    productAccess: 'Product Access',
    createdBy: 'Created By',
    contactDetails: 'Contact Details',
    address: 'Address',
    stateCity: 'State/City',
    mobile: 'Mobile',
    paypalEmail: 'Paypal Email',
    website: 'Website',
    interest: 'Interest',
  },
  editProfile: {
    headerTitle: 'Edit Profile',
    userInfo: 'Edit Your Profile Informations',
    editPhoto: 'Choose Photo',
    firstName: 'First Name',
    lastName: 'Last Name',
    mobileNumber: 'Mobile Number',
    email: 'Login Email',
    address: 'Address',
    state: 'State',
    city: 'City',
    website: 'Website',
    interest: 'Add it to your Interest',
    zipCode: 'Zip Code',
    updateBtnName: 'Update',
  },
  referAndEarn: {
    headerTitle: 'Refer & Earn',
    userInfo: 'Refer User & Earn Money',
    name: 'Name',
    mobileNumber: 'Mobile Number',
    email: 'Email',
    sendBtnName: 'Send Message',
    linkBtn: 'Click here to view your Referrals',
  },
  myReferrals: {
    headerTitle: 'My Referrals',
    userInfo: 'Your Referrals details',
    dropdownAll: 'All',
    registered: 'Registered',
    notRegistered: 'Not Registered',
    referredOn: 'Referred On: ',
    registeredOn: 'Registered On: ',
  },
  referralCommissions: {
    headerTitle: 'Referral Comissions',
    userInfo: 'Your Referral Commissions',
    rferredUser: 'Referred User: ',
    referralCommission: 'Referral Commission: ',
    status: 'Status: ',
    email: 'Email: ',
    phone: 'Phone: ',
    paymentDate: 'Payment Date: ',
  },
  contactUs: {
    headerTitle: 'Contact Us',
    findUsBtnName: 'Find Us',
    submitBtnName: 'Submit',
    subject: 'Subject',
    message: 'Message',
  },
  payoutHistory: {
    headerTitle: 'Payout History',
    userInfo: 'Transfer Money & View Payout History',
    transferBtnName: 'Transfer to you Paypal Account',
    emailId: 'Your Paypal email Id: ',
    payoutStatus: 'Payout Status:',
    notEnoughAmountTxt:
      'Cannot Tranfer To PayPal Account. Pending Amount is less than Minimum Withdraw Amount',
  },
  faq: {
    headerTitle: 'FAQ',
    userInfo: 'Frequently Asked Questions',
  },
  hamburgerMenu: {
    home: 'Home',
    profile: 'Profile',
    viewProfile: 'View Profile',
    editProfile: 'Edit Profile',
    referrals: 'Referrals',
    referAndEarn: 'Refer & Earn',
    myReferrals: 'My Referrals',
    referralsCommission: 'Referrals Commission',
    commissionAndPayout: 'Commission & Payout',
    viewCommissions: 'View Commissions',
    transferMoney: 'Transfer Money',
    products: 'Products',
    trendingProducts: 'Trending Products',
    contactUs: 'ContactUs',
    FAQs: 'FAQs',
    signOut: 'Sign Out',
  },
  productDetails: {
    headerTitle: 'Product Details',
    productName: 'Product Name',
    amount: 'Amount',
    status: 'Status',
    addToWishList: 'ADD TO WISH LIST',
    sku: 'SKU',
    type: 'TYPE',
    group: 'Group',
    prodStatus: 'Status',
    wishBtnName: 'ADD TO WISH LIST',
  },
  userVerification: {
    headerTitleEmail: 'Email Verification',
    headerTitleMobile: 'Mobile Verification',
    userInfo: 'Please verify your Email',
    userInfoStep: 'Your Registered email is',
    sendVerification: 'Send Verification Code',
    emailStep2: 'Verification Code sent to your registered email',
    emailPlaceHolder: 'Enter your Email verification code',

    userInfoMobile: 'Please verify your Mobile',
    userInfoStepMobile: 'Your Registered Mobile is',
    mobileStep2: 'Verification Code sent to your registered Mobile',
    mobilePlaceHolder: 'Enter your Mobile verification code',
    step2Next: 'Verify Code',
  },
  common: {
    placeHolder: 'Enter value',
    imgPickerTitle: 'Image Picker',
    cameraBtnName: 'Take photo',
    galleryBtnName: 'Choose from photos',
    cancelBtnName: 'Cancel',
  },
};
