import {StyleSheet} from 'react-native';
import {widthAdapter, heightAdapter, fontscale} from '../uttils/adapterUtil';
import Colors from '../uttils/Colors';
import fontFamily from '../uttils/FontFamily';

const styles = StyleSheet.create({
  trendingContainer: {
    flex: 1,
    marginLeft: widthAdapter(40),
    marginRight: widthAdapter(40),
    // paddingTop: heightAdapter(50),
  },
  trendingList: {
    marginTop: heightAdapter(50),
    marginBottom: heightAdapter(160),
    borderColor: 'red',
    borderWidth: 1,
  },
  mainContainer: {
    alignItems: 'center',
    // borderWidth: 1,
    // borderColor: 'gray',
  },
  topContainer: {
    flexDirection: 'row',
    width: heightAdapter(745),
    // marginBottom: widthAdapter(75),
    // alignItems: 'center',
    // justifyContent: 'center',
    // width: '100%',
    // borderRadius: widthAdapter(4),
    // borderWidth: 1,
    // borderBottomWidth: widthAdapter(5),
    // borderColor: 'red',
    // paddingTop: widthAdapter(30),
    // paddingBottom: widthAdapter(30),
    // paddingLeft: widthAdapter(10),
    // borderWidth: 1,
    // borderColor: 'red',
  },
  leftViewContainer: {
    width: widthAdapter(500),
    // borderColor: 'green',
    // borderWidth: 1,
  },
  rightViewContainer: {
    width: widthAdapter(245),
    // height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'green',
  },
  trendingImage: {
    height: heightAdapter(100),
    width: widthAdapter(100),
  },
  productView: {
    flexDirection: 'row',
    width: '100%',
    // height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    // borderColor: 'red',
    // borderWidth: 1,
    // marginBottom: heightAdapter(20),
  },
  productNameTxt: {
    fontFamily: fontFamily.primaryFontFamily,
    color: '#333',
    fontWeight: '700',
    fontSize: fontscale(17),
  },
  dotWithTick: {
    height: widthAdapter(40),
    width: widthAdapter(40),
    // backgroundColor: Colors.primaryAppColor,
    // borderRadius: 100,
    marginRight: widthAdapter(20),
    marginLeft: widthAdapter(20),
  },
  amountStatusContainer: {
    flexDirection: 'row',
    // width: '100%',
    // height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: widthAdapter(90),
    // marginBottom: heightAdapter(20),
    // borderColor: 'red',
    // borderWidth: 1,
  },
  amountLabel: {
    fontSize: fontscale(14),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.black,
    fontWeight: '500',
  },
  dollar: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: 'green',
    fontWeight: '500',
  },
  amount: {
    fontSize: fontscale(14),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.primaryAppColor,
    fontWeight: 'bold',
  },
  statusLabel: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.primaryAppColor,
    fontWeight: '500',
  },
  status: {
    fontSize: widthAdapter(35),
    fontFamily: fontFamily.primaryFontFamily,
    color: 'green',
    fontWeight: '500',
  },
  trendingStatusContainer: {
    flexDirection: 'row',
    // width: '100%',
    // height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: widthAdapter(90),
    // marginBottom: heightAdapter(20),
    // borderWidth: 1,
    // borderColor: 'blue',
  },
  skuContainer: {
    flexDirection: 'row',
    // width: '100%',
    // height: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: widthAdapter(90),
    // marginBottom: heightAdapter(20),
    // borderWidth: 1,
    // borderColor: 'red',
  },
  skuLabel: {
    fontSize: fontscale(14),
    fontFamily: fontFamily.primaryFontFamily,
    color: '#a6a6a6',
    fontWeight: '500',
  },

  productDetailsContainer: {
    flex: 1,
    marginLeft: widthAdapter(40),
    marginRight: widthAdapter(40),
    paddingTop: heightAdapter(50),
    // borderColor: 'red',
    // borderWidth: 1,
  },
  productNameLabel: {
    fontFamily: fontFamily.primaryFontFamily,
    fontSize: fontscale(15),
    color: '#737373',
    // lineHeight: 1,
  },
  // productName: {
  //   fontFamily: fontFamily.primaryFontFamily,
  //   fontSize: fontscale(25),
  //   // color: '#737373',
  // },
  amountContainer: {
    flexDirection: 'row',
    // borderColor: 'red',
    // borderWidth: 1,
    justifyContent: 'flex-end',
  },
  commissionAmountLabel: {
    fontFamily: fontFamily.primaryFontFamily,
    fontSize: fontscale(15),
    color: '#737373',
    // lineHeight: 1,
  },
  commissionAmount: {
    fontSize: fontscale(21),
    fontFamily: fontFamily.primaryFontFamily,
    color: Colors.primaryAppColor,
    fontWeight: '500',
  },
  commissionStatusContainer: {
    flexDirection: 'row',
    // borderColor: 'red',
    // borderWidth: 1,
    justifyContent: 'flex-end',
  },
  imageContainer: {
    flexDirection: 'row',
    borderColor: '#ccc',
    borderWidth: 0.3,
    justifyContent: 'center',
    padding: widthAdapter(20),
  },
  productImage: {
    height: heightAdapter(150),
    width: widthAdapter(200),
  },
  addWishListBtn: {
    borderWidth: 1,
    borderColor: '#ccc',
    width: widthAdapter(300),
    height: heightAdapter(75),
    borderRadius: heightAdapter(5),
    backgroundColor: '#fff',
  },
  addWishListBtnText: {
    color: '#333',
    fontSize: fontscale(13),
    fontFamily: fontFamily.primaryFontFamily,
  },
  labelContainer: {
    flexDirection: 'row',
    width: '100%',
  },
  viewStyle: {
    width: '50%',
    backgroundColor: '#f9f9f9',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
    paddingLeft: widthAdapter(20),
    paddingRight: widthAdapter(20),
  },
  label: {
    fontSize: fontscale(15),
    fontWeight: 'bold',
    fontFamily: fontFamily.primaryFontFamily,
  },
  value: {
    fontSize: fontscale(15),
    fontFamily: fontFamily.primaryFontFamily,
  },
  productInfoContainer: {
    borderColor: '#ccc',
    borderWidth: 0.3,
  },
  transMessageContainer: {
    width: widthAdapter(600),
    borderColor: '#d7d9da',
    borderBottomWidth: 1,
    borderTopWidth: 1,
    marginBottom: heightAdapter(50),
    marginTop: heightAdapter(50),
    alignItems: 'center',
    justifyContent: 'center',
    padding: widthAdapter(5),
    backgroundColor: '#f6f6f6',
  },
  transMessage: {
    fontSize: fontscale(15),
    color: '#262626',
    fontWeight: 'bold',
  },
  totalView: {
    width: widthAdapter(600),
    height: heightAdapter(100),
    borderWidth: 2,
    borderColor: 'red',
  },
});

export default styles;
